[package]
name = "seelauncherplus"
version = "1.0.0"
edition = "2024"
default-run = "seelauncherplus-launcher"

[[bin]]
name = "seelauncherplus-launcher"
path = "src/launcher.rs"

[dependencies]
seelauncherplus-lib = { path = "./lib" }
reqwest = { version = "0.13.5", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
text_io = "0.1.13"
mslnk = "0.1.8"
dirs = "7.0.0"
rfd = "0.17.2"


[build-dependencies]
winresource = "0.1.31"

[package.metadata.winresource]
ProductName = "SeeLauncher+"
LegalCopyright = "Áhh, mi ilyen szerrel nem élünk."
